<?php
/**
 * High Price Products widget module
 * 
 * @category    Gmc
 * @package     Gmc_TopExpensiveProducts
 * @copyright   Copyright (c) 2018 Marius Grad
 */

$products = $this->getProductCollection();
?>
<?php if ($products && $products->getSize()): ?>
<div class="widget widget-expensive-products">
    <div class="widget-title">
        <h2><?php echo $this->__('Expensive Products') ?></h2>
    </div>
    <div class="widget-products">
    <?php $columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($products->getItems() as $product): ?>
        <?php if ($i++%$columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$columnCount==0): ?> first<?php elseif($i%$columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $product->getProductUrl() ?>" 
                   title="<?php echo $this->stripTags($product->getName(), null, true) ?>" 
                   class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(85) ?>" 
                        width="85" 
                        height="85" 
                        alt="<?php echo $this->stripTags($product->getName(), null, true) ?>" />
                </a>
                <h3 class="product-name">
                    <a href="<?php echo $product->getProductUrl() ?>" 
                       title="<?php echo $this->stripTags($product->getName(), null, true) ?>)">
                           <?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName() , 'name') ?>
                    </a>
                </h3>
                <?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
                <?php echo $this->getPriceHtml($product, true, '-widget-new-grid') ?>
            </li>
        <?php if ($i%$columnCount==0 || $i==count($products)): ?>
        </ul>
        <?php endif ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; 
